### PR TITLE
Added version numbers

### PR DESCRIPTION
**Pull request by florianjehn**
unconstrained install run into problems with conflicting versions

### CODE REVIEW

**Review by mmaelicke — CHANGES_REQUESTED** [review]
Fixing exact version number is not working for me, as the code runs on different machines. I guess to avoid conflicts, we should rather add minimum version requirements like `pandas>=0.6.0`. 
Also, my pandas is older and works without issues.

Do you know which dependency caused problems for you?

**Comment by florianjehn** [comment]
Hmmm probably minimal and maximal version. The conflict was between pandas and numpy and pandas and pytz.

I installed it in a virtual environment with conda. Maybe this was the problem?

**Comment by mmaelicke** [comment]
> I installed it in a virtual environment with conda. Maybe this was the problem?

Interesting. Did the same thing...

**Comment by florianjehn** [comment]
Then I am confused why you are not using an environment.yml instead of requirements. When setting up my virtual environments I follow the Good Research Code Handbook: https://goodresearch.dev/setup.html

**Comment by mmaelicke** [comment]
> Then I am confused why you are not using an environment.yml instead of requirements. When setting up my virtual environments I follow the Good Research Code Handbook: https://goodresearch.dev/setup.html

Yeah, on my working machine it is done very similarly. Yet, environment.yml and conda are in my opinion not always the best tool when working in containerized environements. Software running on my servers, like the hub on hub.camels-de.org, is actually spread across more than one container and not all of them use conda, or the same python versions. Thus, I personally use requirements.txt more often, because it is more flexible in this sense. 
Fixing requirements to specific versions would make updates a day-lasting task if you manage more than one machine. Thus, I usually have only minimum versions where they are absolutely need, and keep versions unconstrained whenever possible. Only if I share, ie. reseach code, or deploy an application in production, I use a pip freeze to fix exact versions for *all* dependencies in order to be reproducible.

But you are welcome to commit a environment.yml into the repo, which I would just ignore where not suitable and can be used when working with conda.

**Comment by florianjehn** [comment]
Makes sense. Than I'll withdraw this pull request and make a new one with an environment.yml

**Pull request closed without merging**
