### PR TITLE
Added notebook 

### PR DESCRIPTION
**Pull request by florianjehn**
density.ipnyb looks how long the time series are overall
data_gaps.ipnyb looks many gaps q and p data has

data gaps does not run on my computer, as it somehow cannot read in the files. Not sure why, as the data is locally here. But would be great if @mmaelicke could run it on his computer if it works there.

### CODE REVIEW

**Comment by mmaelicke** [comment]
nice, thanks, I'll have a look!

**Comment by mmaelicke** [comment]
@florianjehn nice!
 I added a little bit to your notebooks, for density I added a plotly figure that I will use on the website and for gaps I found the problem.

You set the `problem_encountered` flag whenever something went wrong. So even if q was there but w not, **both** were set to NaN. The variable for water level is called 'w', not 'p' (.... I know....), therefore the code could never find 'p' and always set NA.

Now it works and only fails for the files, where we actually have a problem. 
I changed the logic to not set Na, but `100`, meaning `100%` of gaps in case something went wrong. Is that actually correct? do you calculate the amount of gaps or the amount of data :) ?

**Comment by florianjehn** [comment]
Thanks for the fix. I meant to program it that way that it tells you much data exists between the first and last valid entry. So, for example if you have the timeseries:

`time_series = [1, 2, np.nan, 3, 4, np.nan, 5, 6, np.nan]`

It would tell you that 25 % of the data are gaps. Or what did you have in mind?

**Comment by mmaelicke** [comment]
> Thanks for the fix. I meant to program it that way that it tells you much data exists between the first and last valid entry. So, for example if you have the timeseries:
> 
> `time_series = [1, 2, np.nan, 3, 4, np.nan, 5, 6, np.nan]`
> 
> It would tell you that 25 % of the data are gaps. Or what did you have in mind?

Ah, I see. That is quite smart as it automatically omits NaNs at the start and end of the timeseries. Did not think of that. But then putting 100 for missing timeseries is good, right? @florianjehn you agree? then I merge the PR

**Comment by florianjehn** [comment]
Yes, 100 for a missing timeseries totally makes sense :+1:

**Pull request merged**
